// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/m-mizutani/gollem"
	"sync"
)

// LLMClientMock is a mock implementation of gollem.LLMClient.
//
//	func TestSomethingThatUsesLLMClient(t *testing.T) {
//
//		// make and configure a mocked gollem.LLMClient
//		mockedLLMClient := &LLMClientMock{
//			GenerateEmbeddingFunc: func(ctx context.Context, dimension int, input []string) ([][]float64, error) {
//				panic("mock out the GenerateEmbedding method")
//			},
//			NewSessionFunc: func(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error) {
//				panic("mock out the NewSession method")
//			},
//		}
//
//		// use mockedLLMClient in code that requires gollem.LLMClient
//		// and then make assertions.
//
//	}
type LLMClientMock struct {
	// GenerateEmbeddingFunc mocks the GenerateEmbedding method.
	GenerateEmbeddingFunc func(ctx context.Context, dimension int, input []string) ([][]float64, error)

	// NewSessionFunc mocks the NewSession method.
	NewSessionFunc func(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateEmbedding holds details about calls to the GenerateEmbedding method.
		GenerateEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dimension is the dimension argument value.
			Dimension int
			// Input is the input argument value.
			Input []string
		}
		// NewSession holds details about calls to the NewSession method.
		NewSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options []gollem.SessionOption
		}
	}
	lockGenerateEmbedding sync.RWMutex
	lockNewSession        sync.RWMutex
}

// GenerateEmbedding calls GenerateEmbeddingFunc.
func (mock *LLMClientMock) GenerateEmbedding(ctx context.Context, dimension int, input []string) ([][]float64, error) {
	callInfo := struct {
		Ctx       context.Context
		Dimension int
		Input     []string
	}{
		Ctx:       ctx,
		Dimension: dimension,
		Input:     input,
	}
	mock.lockGenerateEmbedding.Lock()
	mock.calls.GenerateEmbedding = append(mock.calls.GenerateEmbedding, callInfo)
	mock.lockGenerateEmbedding.Unlock()
	if mock.GenerateEmbeddingFunc == nil {
		var (
			float64ssOut [][]float64
			errOut       error
		)
		return float64ssOut, errOut
	}
	return mock.GenerateEmbeddingFunc(ctx, dimension, input)
}

// GenerateEmbeddingCalls gets all the calls that were made to GenerateEmbedding.
// Check the length with:
//
//	len(mockedLLMClient.GenerateEmbeddingCalls())
func (mock *LLMClientMock) GenerateEmbeddingCalls() []struct {
	Ctx       context.Context
	Dimension int
	Input     []string
} {
	var calls []struct {
		Ctx       context.Context
		Dimension int
		Input     []string
	}
	mock.lockGenerateEmbedding.RLock()
	calls = mock.calls.GenerateEmbedding
	mock.lockGenerateEmbedding.RUnlock()
	return calls
}

// NewSession calls NewSessionFunc.
func (mock *LLMClientMock) NewSession(ctx context.Context, options ...gollem.SessionOption) (gollem.Session, error) {
	callInfo := struct {
		Ctx     context.Context
		Options []gollem.SessionOption
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockNewSession.Lock()
	mock.calls.NewSession = append(mock.calls.NewSession, callInfo)
	mock.lockNewSession.Unlock()
	if mock.NewSessionFunc == nil {
		var (
			sessionOut gollem.Session
			errOut     error
		)
		return sessionOut, errOut
	}
	return mock.NewSessionFunc(ctx, options...)
}

// NewSessionCalls gets all the calls that were made to NewSession.
// Check the length with:
//
//	len(mockedLLMClient.NewSessionCalls())
func (mock *LLMClientMock) NewSessionCalls() []struct {
	Ctx     context.Context
	Options []gollem.SessionOption
} {
	var calls []struct {
		Ctx     context.Context
		Options []gollem.SessionOption
	}
	mock.lockNewSession.RLock()
	calls = mock.calls.NewSession
	mock.lockNewSession.RUnlock()
	return calls
}

// SessionMock is a mock implementation of gollem.Session.
//
//	func TestSomethingThatUsesSession(t *testing.T) {
//
//		// make and configure a mocked gollem.Session
//		mockedSession := &SessionMock{
//			AppendHistoryFunc: func(history *gollem.History) error {
//				panic("mock out the AppendHistory method")
//			},
//			CountTokenFunc: func(ctx context.Context, input ...gollem.Input) (int, error) {
//				panic("mock out the CountToken method")
//			},
//			GenerateFunc: func(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (*gollem.Response, error) {
//				panic("mock out the Generate method")
//			},
//			StreamFunc: func(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (<-chan *gollem.Response, error) {
//				panic("mock out the Stream method")
//			},
//			HistoryFunc: func() (*gollem.History, error) {
//				panic("mock out the History method")
//			},
//		}
//
//		// use mockedSession in code that requires gollem.Session
//		// and then make assertions.
//
//	}
type SessionMock struct {
	// AppendHistoryFunc mocks the AppendHistory method.
	AppendHistoryFunc func(history *gollem.History) error

	// CountTokenFunc mocks the CountToken method.
	CountTokenFunc func(ctx context.Context, input ...gollem.Input) (int, error)

	// GenerateFunc mocks the Generate method.
	GenerateFunc func(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (*gollem.Response, error)

	// StreamFunc mocks the Stream method.
	StreamFunc func(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (<-chan *gollem.Response, error)

	// HistoryFunc mocks the History method.
	HistoryFunc func() (*gollem.History, error)

	// calls tracks calls to the methods.
	calls struct {
		// AppendHistory holds details about calls to the AppendHistory method.
		AppendHistory []struct {
			// History is the history argument value.
			History *gollem.History
		}
		// CountToken holds details about calls to the CountToken method.
		CountToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []gollem.Input
		}
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []gollem.Input
			// Opts is the opts argument value.
			Opts []gollem.GenerateOption
		}
		// Stream holds details about calls to the Stream method.
		Stream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input []gollem.Input
			// Opts is the opts argument value.
			Opts []gollem.GenerateOption
		}
		// History holds details about calls to the History method.
		History []struct {
		}
	}
	lockAppendHistory sync.RWMutex
	lockCountToken    sync.RWMutex
	lockGenerate      sync.RWMutex
	lockStream        sync.RWMutex
	lockHistory       sync.RWMutex
}

// AppendHistory calls AppendHistoryFunc.
func (mock *SessionMock) AppendHistory(history *gollem.History) error {
	callInfo := struct {
		History *gollem.History
	}{
		History: history,
	}
	mock.lockAppendHistory.Lock()
	mock.calls.AppendHistory = append(mock.calls.AppendHistory, callInfo)
	mock.lockAppendHistory.Unlock()
	if mock.AppendHistoryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AppendHistoryFunc(history)
}

// AppendHistoryCalls gets all the calls that were made to AppendHistory.
// Check the length with:
//
//	len(mockedSession.AppendHistoryCalls())
func (mock *SessionMock) AppendHistoryCalls() []struct {
	History *gollem.History
} {
	var calls []struct {
		History *gollem.History
	}
	mock.lockAppendHistory.RLock()
	calls = mock.calls.AppendHistory
	mock.lockAppendHistory.RUnlock()
	return calls
}

// CountToken calls CountTokenFunc.
func (mock *SessionMock) CountToken(ctx context.Context, input ...gollem.Input) (int, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []gollem.Input
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCountToken.Lock()
	mock.calls.CountToken = append(mock.calls.CountToken, callInfo)
	mock.lockCountToken.Unlock()
	if mock.CountTokenFunc == nil {
		var (
			nOut   int
			errOut error
		)
		return nOut, errOut
	}
	return mock.CountTokenFunc(ctx, input...)
}

// CountTokenCalls gets all the calls that were made to CountToken.
// Check the length with:
//
//	len(mockedSession.CountTokenCalls())
func (mock *SessionMock) CountTokenCalls() []struct {
	Ctx   context.Context
	Input []gollem.Input
} {
	var calls []struct {
		Ctx   context.Context
		Input []gollem.Input
	}
	mock.lockCountToken.RLock()
	calls = mock.calls.CountToken
	mock.lockCountToken.RUnlock()
	return calls
}

// Generate calls GenerateFunc.
func (mock *SessionMock) Generate(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (*gollem.Response, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []gollem.Input
		Opts  []gollem.GenerateOption
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	if mock.GenerateFunc == nil {
		var (
			responseOut *gollem.Response
			errOut      error
		)
		return responseOut, errOut
	}
	return mock.GenerateFunc(ctx, input, opts...)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedSession.GenerateCalls())
func (mock *SessionMock) GenerateCalls() []struct {
	Ctx   context.Context
	Input []gollem.Input
	Opts  []gollem.GenerateOption
} {
	var calls []struct {
		Ctx   context.Context
		Input []gollem.Input
		Opts  []gollem.GenerateOption
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Stream calls StreamFunc.
func (mock *SessionMock) Stream(ctx context.Context, input []gollem.Input, opts ...gollem.GenerateOption) (<-chan *gollem.Response, error) {
	callInfo := struct {
		Ctx   context.Context
		Input []gollem.Input
		Opts  []gollem.GenerateOption
	}{
		Ctx:   ctx,
		Input: input,
		Opts:  opts,
	}
	mock.lockStream.Lock()
	mock.calls.Stream = append(mock.calls.Stream, callInfo)
	mock.lockStream.Unlock()
	if mock.StreamFunc == nil {
		var (
			responseChOut <-chan *gollem.Response
			errOut        error
		)
		return responseChOut, errOut
	}
	return mock.StreamFunc(ctx, input, opts...)
}

// StreamCalls gets all the calls that were made to Stream.
// Check the length with:
//
//	len(mockedSession.StreamCalls())
func (mock *SessionMock) StreamCalls() []struct {
	Ctx   context.Context
	Input []gollem.Input
	Opts  []gollem.GenerateOption
} {
	var calls []struct {
		Ctx   context.Context
		Input []gollem.Input
		Opts  []gollem.GenerateOption
	}
	mock.lockStream.RLock()
	calls = mock.calls.Stream
	mock.lockStream.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *SessionMock) History() (*gollem.History, error) {
	callInfo := struct {
	}{}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	if mock.HistoryFunc == nil {
		var (
			historyOut *gollem.History
			errOut     error
		)
		return historyOut, errOut
	}
	return mock.HistoryFunc()
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedSession.HistoryCalls())
func (mock *SessionMock) HistoryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}

// ToolMock is a mock implementation of gollem.Tool.
//
//	func TestSomethingThatUsesTool(t *testing.T) {
//
//		// make and configure a mocked gollem.Tool
//		mockedTool := &ToolMock{
//			RunFunc: func(ctx context.Context, args map[string]any) (map[string]any, error) {
//				panic("mock out the Run method")
//			},
//			SpecFunc: func() gollem.ToolSpec {
//				panic("mock out the Spec method")
//			},
//		}
//
//		// use mockedTool in code that requires gollem.Tool
//		// and then make assertions.
//
//	}
type ToolMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, args map[string]any) (map[string]any, error)

	// SpecFunc mocks the Spec method.
	SpecFunc func() gollem.ToolSpec

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args map[string]any
		}
		// Spec holds details about calls to the Spec method.
		Spec []struct {
		}
	}
	lockRun  sync.RWMutex
	lockSpec sync.RWMutex
}

// Run calls RunFunc.
func (mock *ToolMock) Run(ctx context.Context, args map[string]any) (map[string]any, error) {
	callInfo := struct {
		Ctx  context.Context
		Args map[string]any
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		var (
			stringToVOut map[string]any
			errOut       error
		)
		return stringToVOut, errOut
	}
	return mock.RunFunc(ctx, args)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedTool.RunCalls())
func (mock *ToolMock) RunCalls() []struct {
	Ctx  context.Context
	Args map[string]any
} {
	var calls []struct {
		Ctx  context.Context
		Args map[string]any
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Spec calls SpecFunc.
func (mock *ToolMock) Spec() gollem.ToolSpec {
	callInfo := struct {
	}{}
	mock.lockSpec.Lock()
	mock.calls.Spec = append(mock.calls.Spec, callInfo)
	mock.lockSpec.Unlock()
	if mock.SpecFunc == nil {
		var (
			toolSpecOut gollem.ToolSpec
		)
		return toolSpecOut
	}
	return mock.SpecFunc()
}

// SpecCalls gets all the calls that were made to Spec.
// Check the length with:
//
//	len(mockedTool.SpecCalls())
func (mock *ToolMock) SpecCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSpec.RLock()
	calls = mock.calls.Spec
	mock.lockSpec.RUnlock()
	return calls
}

// StrategyMock is a mock implementation of gollem.Strategy.
//
//	func TestSomethingThatUsesStrategy(t *testing.T) {
//
//		// make and configure a mocked gollem.Strategy
//		mockedStrategy := &StrategyMock{
//			HandleFunc: func(ctx context.Context, state *gollem.StrategyState) ([]gollem.Input, *gollem.ExecuteResponse, error) {
//				panic("mock out the Handle method")
//			},
//			InitFunc: func(ctx context.Context, inputs []gollem.Input) error {
//				panic("mock out the Init method")
//			},
//			ToolsFunc: func(ctx context.Context) ([]gollem.Tool, error) {
//				panic("mock out the Tools method")
//			},
//		}
//
//		// use mockedStrategy in code that requires gollem.Strategy
//		// and then make assertions.
//
//	}
type StrategyMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, state *gollem.StrategyState) ([]gollem.Input, *gollem.ExecuteResponse, error)

	// InitFunc mocks the Init method.
	InitFunc func(ctx context.Context, inputs []gollem.Input) error

	// ToolsFunc mocks the Tools method.
	ToolsFunc func(ctx context.Context) ([]gollem.Tool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *gollem.StrategyState
		}
		// Init holds details about calls to the Init method.
		Init []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inputs is the inputs argument value.
			Inputs []gollem.Input
		}
		// Tools holds details about calls to the Tools method.
		Tools []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockHandle sync.RWMutex
	lockInit   sync.RWMutex
	lockTools  sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *StrategyMock) Handle(ctx context.Context, state *gollem.StrategyState) ([]gollem.Input, *gollem.ExecuteResponse, error) {
	callInfo := struct {
		Ctx   context.Context
		State *gollem.StrategyState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	if mock.HandleFunc == nil {
		var (
			inputsOut          []gollem.Input
			executeResponseOut *gollem.ExecuteResponse
			errOut             error
		)
		return inputsOut, executeResponseOut, errOut
	}
	return mock.HandleFunc(ctx, state)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedStrategy.HandleCalls())
func (mock *StrategyMock) HandleCalls() []struct {
	Ctx   context.Context
	State *gollem.StrategyState
} {
	var calls []struct {
		Ctx   context.Context
		State *gollem.StrategyState
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}

// Init calls InitFunc.
func (mock *StrategyMock) Init(ctx context.Context, inputs []gollem.Input) error {
	callInfo := struct {
		Ctx    context.Context
		Inputs []gollem.Input
	}{
		Ctx:    ctx,
		Inputs: inputs,
	}
	mock.lockInit.Lock()
	mock.calls.Init = append(mock.calls.Init, callInfo)
	mock.lockInit.Unlock()
	if mock.InitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InitFunc(ctx, inputs)
}

// InitCalls gets all the calls that were made to Init.
// Check the length with:
//
//	len(mockedStrategy.InitCalls())
func (mock *StrategyMock) InitCalls() []struct {
	Ctx    context.Context
	Inputs []gollem.Input
} {
	var calls []struct {
		Ctx    context.Context
		Inputs []gollem.Input
	}
	mock.lockInit.RLock()
	calls = mock.calls.Init
	mock.lockInit.RUnlock()
	return calls
}

// Tools calls ToolsFunc.
func (mock *StrategyMock) Tools(ctx context.Context) ([]gollem.Tool, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTools.Lock()
	mock.calls.Tools = append(mock.calls.Tools, callInfo)
	mock.lockTools.Unlock()
	if mock.ToolsFunc == nil {
		var (
			toolsOut []gollem.Tool
			errOut   error
		)
		return toolsOut, errOut
	}
	return mock.ToolsFunc(ctx)
}

// ToolsCalls gets all the calls that were made to Tools.
// Check the length with:
//
//	len(mockedStrategy.ToolsCalls())
func (mock *StrategyMock) ToolsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTools.RLock()
	calls = mock.calls.Tools
	mock.lockTools.RUnlock()
	return calls
}
