# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - mock
  mock:
    desc: Generate mock files
    cmds:
      - go run github.com/matryer/moq@v0.5.3
        -out ./mock/mock_gen.go
        -pkg mock
        -rm -skip-ensure -stub
        .
        LLMClient Session Tool Strategy
      # OpenAI package apiClient mock generation
      - go run github.com/matryer/moq@v0.5.3
        -out ./llm/openai/mock_gen_test.go
        -pkg openai_test
        -rm -skip-ensure
        ./llm/openai
        apiClient
      # Claude package apiClient mock generation
      - go run github.com/matryer/moq@v0.5.3
        -out ./llm/claude/mock_gen_test.go
        -pkg claude_test
        -rm -skip-ensure
        ./llm/claude
        apiClient
      # Gemini package apiClient mock generation
      - go run github.com/matryer/moq@v0.5.3
        -out ./llm/gemini/mock_gen_test.go
        -pkg gemini_test
        -rm -skip-ensure
        ./llm/gemini
        apiClient
  viewer:build:
    desc: Build the trace viewer frontend
    dir: cmd/gollem/frontend
    cmds:
      - pnpm install
      - pnpm build
  viewer:dev:
    desc: Start the trace viewer frontend dev server
    dir: cmd/gollem/frontend
    cmds:
      - pnpm dev
