package react

import (
	"time"

	"github.com/m-mizutani/gollem"
)

// TAOEntry represents a single Thought-Action-Observation cycle entry
type TAOEntry struct {
	Iteration   int              `json:"iteration"`
	Thought     *ThoughtData     `json:"thought,omitempty"`
	Action      *ActionData      `json:"action,omitempty"`
	Observation *ObservationData `json:"observation,omitempty"`
	Timestamp   time.Time        `json:"timestamp"`
}

// ThoughtData represents the reasoning process of the LLM
type ThoughtData struct {
	Content   string `json:"content"`   // The thought content generated by LLM
	Reasoning string `json:"reasoning"` // The reasoning process
}

// ActionType represents the type of action taken
type ActionType string

const (
	// ActionTypeToolCall indicates the action is calling one or more tools
	ActionTypeToolCall ActionType = "tool_call"
	// ActionTypeRespond indicates the action is responding to the user
	ActionTypeRespond ActionType = "respond"
)

// ActionData represents the action taken by the LLM
type ActionData struct {
	Type      ActionType             `json:"type"`
	ToolCalls []*gollem.FunctionCall `json:"tool_calls,omitempty"`
	Response  string                 `json:"response,omitempty"`
}

// ObservationData represents the results observed from actions
type ObservationData struct {
	ToolResults []ToolResult `json:"tool_results"`
	Success     bool         `json:"success"`
	Error       string       `json:"error,omitempty"`
}

// ToolResult represents the result of a single tool execution
type ToolResult struct {
	ToolName string `json:"tool_name"`
	Success  bool   `json:"success"`
	Output   string `json:"output"`
	Error    string `json:"error,omitempty"`
}

// TraceExport represents the exportable trace data
type TraceExport struct {
	Entries  []TAOEntry    `json:"entries"`
	Summary  TraceSummary  `json:"summary"`
	Metadata TraceMetadata `json:"metadata"`
}

// TraceSummary contains summary statistics of the trace
type TraceSummary struct {
	TotalIterations int           `json:"total_iterations"`
	ToolCallsCount  int           `json:"tool_calls_count"`
	SuccessRate     float64       `json:"success_rate"`
	Duration        time.Duration `json:"duration"`
}

// TraceMetadata contains metadata about the trace execution
type TraceMetadata struct {
	Strategy       string    `json:"strategy"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
	CompletionType string    `json:"completion_type"` // "success", "max_iterations", "loop_detected", "error"
}

// FewShotExample represents a single few-shot learning example
type FewShotExample struct {
	Question    string `json:"question"`
	Thought     string `json:"thought"`
	Action      string `json:"action"`
	Observation string `json:"observation"`
	Answer      string `json:"answer"`
}

// Strategy implements the ReAct (Reasoning and Acting) pattern
type Strategy struct {
	// LLM client
	llm gollem.LLMClient

	// Configuration
	maxIterations      int
	maxRepeatedActions int
	enableFewShot      bool
	fewShotExamples    []FewShotExample

	// Prompt templates
	systemPrompt      string
	thoughtPrompt     string
	observationPrompt string

	// Trace management
	trace        []TAOEntry
	currentEntry *TAOEntry
	startTime    time.Time
	endTime      time.Time

	// Loop detection
	actionHistory []string
	repeatedCount map[string]int

	// Error tracking
	consecutiveErrors int
}
